export default {
  TEMPERATURE: 'TEMPERATURE',
  PRESSURE: 'PRESSURE',
  HUMIDITY: 'HUMIDITY',
  ACCELEROMETER: 'ACCELEROMETER',
  MAGNETOMETER: 'MAGNETOMETER',
  GYROSCOPE: 'GYROSCOPE',
  DIGITAL_INPUT: 'DIGITAL_INPUT'
}
